python -m torch.distributed.launch --master_port=23458 \
    --nproc_per_node=1 \
    --use_env main.py \
    --dataset_config /home/ma-user/work/zzz/scene/configs/tdod_coco.json \
    --train_batch_size 30  \
    --valid_batch_size 30 \
    --load ckpt/1144_np_dis.pth \
    --ema --text_encoder_lr 1e-5 --lr 1e-5 --lr_fusion 1e-5\
    --num_workers 4 \
    --output-dir 'logs/detection/sth/afford' \
    --eval_skip 1 \
    --load_word_full \
    --fusion --verb_att \